// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvpDEKylRRoDv-QaXCZn8LnsM1PjXzLA',
    appId: '1:501812567429:web:3ce00d74cdcbd6436838ec',
    messagingSenderId: '501812567429',
    projectId: 'smart-bin-lab',
    authDomain: 'smart-bin-lab.firebaseapp.com',
    storageBucket: 'smart-bin-lab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIN9K9O44pmx_d5mMhEiTnvwPepFG7o5s',
    appId: '1:501812567429:android:c08a7c83f00aaf756838ec',
    messagingSenderId: '501812567429',
    projectId: 'smart-bin-lab',
    storageBucket: 'smart-bin-lab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvpDEKylRRoDv-QaXCZn8LnsM1PjXzLA',
    appId: '1:501812567429:web:5dbfac0b392f05bf6838ec',
    messagingSenderId: '501812567429',
    projectId: 'smart-bin-lab',
    authDomain: 'smart-bin-lab.firebaseapp.com',
    storageBucket: 'smart-bin-lab.firebasestorage.app',
  );
}
